on: [ push, pull_request ]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Hello world action step
        id: hello
        uses: ZeroTrepidation/hello-world-javascript-action/actions/hello-world@main
        with:
          who-to-greet: 'Hi ZeroTrepidation'
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"

  goodbye_world_job:
    runs-on: ubuntu-latest
    name: A job to say goodbye
    steps:
      - name: Goodbye world action step
        id: hello
        uses: ZeroTrepidation/hello-world-javascript-action/actions/goodbye-world@main
        with:
          who-to-greet: 'Hi ZeroTrepidation'
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
